#################################################################################################################################
#  																                                                                                              #
# Description: Compose which starts up two containers with web service and one proxy with forwarded ports                       #
# Author: Marcus Costa														                                                                              #
# Email Address: marcus.asc@gmail.com												                                                                    #
# 																                                                                                              #
#################################################################################################################################

version: "3"
networks:
  prxnet:
    driver: bridge
services:
  proxy:
    image: nginx
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    - ./etc/nginx/sites-available:/etc/nginx/sites-enabled
    ports:
    - "80:80"
    hostname: "srvproxy"
    environment:
    - NGINX_HOST=proxy.teste.local
    - NGINX_PORT=80
    networks:
     - prxnet
  web1:
    build:
      context: .
    image: nginx
    volumes:
    - ./web1.html:/usr/share/nginx/html/index.html
    hostname: "srvweb1"
    environment:
    - NGINX_HOST=web1.teste.local
    - NGINX_PORT=80
    networks:
     - prxnet
  web2:
    build:
      context: .
    image: nginx
    volumes:
    - ./web2.html:/usr/share/nginx/html/index.html
    hostname: "srvweb2"
    environment:
    - NGINX_HOST=web2.teste.local
    - NGINX_PORT=80
    networks:
    - prxnet
